name: Deploy to Production

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-via-wireguard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install WireGuard
        uses: egor-tensin/setup-wireguard@v1
        with:
          ips: 10.60.193.2/24
          endpoint: ${{ secrets.WG_ENDPOINT }}
          endpoint_public_key: ${{ secrets.WG_PUBKEY }}
          private_key: ${{ secrets.WG_PRIV_KEY }}
          allowed_ips: 10.60.193.0/24

      - name: Trigger Webhook
        run: |
          curl -X POST http://192.168.35.103:9000/hooks/deploy-prod \
               -H "Content-Type: application/json" \
               -H "X-Token: $WEBHOOK_DEPLOYMENT" \
               --fail \
               --connect-timeout 15 \
               --retry 3
